[package]
name = "rusted_atari"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
bitfield = "0.14.0"
hound = "3.5.1"
sdl2 = "0.35.2"
wav = "1.0.0"

[profile.release]
debug = 1
