[alias]
build-native = "build --release --config ./projects/native/.cargo/config.toml"
build-emscripten = "build --release --config ./projects/emscripten/.cargo/config.toml"
build-windows = "build --release --config ./projects/windows/.cargo/config.toml"

[build]
rustflags=["-Wunused-crate-dependencies"]
