name: Rust

on:
  push:
    branches: [ "master", "javascript_cart_load" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  EM_CONFIG: ${{ github.workspace }}/emscripten_config

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - uses: mymindstorm/setup-emsdk@v14
    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: install_dependencies_01
      run: |
            sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
            sudo apt-get update -y -qq
            sudo apt-get install libsdl2-dev binaryen llvm lld
            rustup target add asmjs-unknown-emscripten
    - name: Build native
      run: cargo build --release --verbose --config projects/native/.cargo/config.toml
    - name: Build javascript
      run: |
           emsdk install latest
           emsdk activate latest
           source emsdk_env.sh
           cargo build --release --verbose --config projects/emscripten/.cargo/config.toml
    
