name: Rust

on:
  push:
    branches: [ "master", "javascript_cart_load" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: install_dependencies_a
      run: sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
    - name: install_dependencies_b
      run: sudo apt-get update -y -qq
    - name: install_dependencies_c
      run: sudo apt-get install libsdl2-dev
    - name: Build native
      run: cargo build --release --verbose --config projects/native/.cargo/config.toml
    - name: Build javascript
      run: cargo build --release --verbose --config projects/emscripten/.cargo/config.toml
    
